### ISSUE TITLE
Support for x.com links

### ISSUE THREAD

**Issue by FiraliaDev** [mozeeshan1/VxT-Bot#10]
Please add support for converting x.com links to fxtwitter.com please! 🙏

Atm, the old twitter.com domain is still fully functional, and I expect it will remain that way for quite some time, if not indefinitely. Would very much appreciate an option to convert the links until x.com gets its own fx/vx!

**Comment by mozeeshan1** [comment]
Hey! I've added the feature. It automatically converts them if you have the toggles for twitter conversion on.
